spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    show-sql: ${SPRING_JPA_SHOW-SQL}
    properties:
      hibernate:
        format_sql: ${SPIRNG_JPA_FORMAT-SQL}
