spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/jenkins_stats
    username: jenkins
    password: jenkins123
  jpa:
    hibernate:
      ddl-auto: update #자동 테이블 생성 옵션
    show-sql: true #SQL 로그 보기
    properties:
      hibernate:
        format_sql: true #SQL 로그 보기
